volumes:
  postgres-data-volume:
  mongo-data-volume:

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      POSTGRES_PASSWORD: LuiCsf5LUikmnI7TGR
      POSTGRES_DB: roadmappr_postgres
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      service.name: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-volume:/data/db
