default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: LuiCsf5LUikmnI7TGR
  host: localhost
  port: 5433
  timeout: 5000

development:
  <<: *default
  database: roadmappr_development

test:
  <<: *default
  database: roadmappr_test

production:
  <<: *default
  port: 5432
  database: roadmappr_production
